### ISSUE TITLE
early stopping

### ISSUE THREAD

**Issue by bioermaf** [mahan-fcb/DSResSol#3]
Epoch 11: early stopping
117/117 [==============================] - 2s 17ms/step
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    model.train()
  File "D:\workspaces\DSResSol\models\SequenceWithBiologicalModel.py", line 100, in train
    y_pred1 = model2.predict([test_pad1, X2]).round().astype(int)
  File "C:\Users\Administrator\.conda\envs\py37\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Administrator\.conda\envs\py37\lib\site-packages\keras\engine\data_adapter.py", line 1655, in _check_data_cardinality
    raise ValueError(msg)
ValueError: Data cardinality is ambiguous:
  x sizes: 3729, 2001
Make sure all arrays contain the same number of samples.

**Comment by sherryliu987** [comment]
Feel free to try https://www.tamarind.bio/dsressol. Tamarind is an online platform for bioinformatics tools that offers computational biology workflows, including DSResSol, for free.
